//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBook()
        {
            this.TblOperations = new HashSet<TblOperation>();
        }
    
        public int bookId { get; set; }
        public string bookName { get; set; }
        public Nullable<byte> bookCategory { get; set; }
        public Nullable<int> bookAuthor { get; set; }
        public string bookRelase { get; set; }
        public string bookPublisher { get; set; }
        public string bookPages { get; set; }
        public Nullable<bool> bookStatus { get; set; }
        public string bookImage { get; set; }
    
        public virtual TblAuthor TblAuthor { get; set; }
        public virtual TblCategory TblCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOperation> TblOperations { get; set; }
    }
}
