//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblContact
    {
        public int contactId { get; set; }
        public string contactName { get; set; }
        public string contactMail { get; set; }
        public string contactNumber { get; set; }
        public string contactContaxt { get; set; }
    }
}
