//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMember()
        {
            this.TblOperations = new HashSet<TblOperation>();
            this.TblPunishments = new HashSet<TblPunishment>();
        }
    
        public int memberId { get; set; }
        public string memberName { get; set; }
        public string memberSurname { get; set; }
        public string memberMail { get; set; }
        public string memberPhone { get; set; }
        public string memberUsername { get; set; }
        public string memberPassword { get; set; }
        public string memberPhoto { get; set; }
        public string memberSchool { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOperation> TblOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPunishment> TblPunishments { get; set; }
    }
}
