//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMessage
    {
        public int messageId { get; set; }
        public string messageReceiver { get; set; }
        public string messageSender { get; set; }
        public string messageSubject { get; set; }
        public string messageContaext { get; set; }
        public Nullable<System.DateTime> messageDate { get; set; }
    }
}
