//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Library.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOperation()
        {
            this.TblPunishments = new HashSet<TblPunishment>();
        }
    
        public int operationId { get; set; }
        public Nullable<int> operationBook { get; set; }
        public Nullable<int> operationMember { get; set; }
        public Nullable<byte> operationEmployee { get; set; }
        public Nullable<System.DateTime> operationGetDate { get; set; }
        public Nullable<System.DateTime> operationBackDate { get; set; }
    
        public virtual TblBook TblBook { get; set; }
        public virtual TblEmployee TblEmployee { get; set; }
        public virtual TblMember TblMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPunishment> TblPunishments { get; set; }
    }
}
